package com.riwi.H4.application.service;

import com.riwi.H4.application.port.in.AuthenticationUseCase;
import com.riwi.H4.application.port.out.UserRepositoryPort;
import com.riwi.H4.domain.model.User;
import com.riwi.H4.domain.exception.DuplicateUsernameException;
import com.riwi.H4.infrastructure.dto.auth.AuthResponse;
import com.riwi.H4.infrastructure.dto.auth.LoginRequest;
import com.riwi.H4.infrastructure.dto.auth.RegisterRequest;
import com.riwi.H4.infrastructure.exception.CustomAuthenticationException;
import com.riwi.H4.infrastructure.security.JwtService;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;

/**
 * Implementation of the AuthenticationUseCase.
 *
 * Handles the business logic for user registration and login.
 * Integrates with UserRepositoryPort, PasswordEncoder, AuthenticationManager, and JwtService.
 *
 * HU5 - TASK 3: Security JWT
 */
@Service
public class AuthenticationServiceImpl implements AuthenticationUseCase {

    private final UserRepositoryPort userRepositoryPort;
    private final PasswordEncoder passwordEncoder;
    private final JwtService jwtService;
    private final AuthenticationManager authenticationManager;
    private final UserDetailsService userDetailsService; // For loading UserDetails

    public AuthenticationServiceImpl(
            UserRepositoryPort userRepositoryPort,
            PasswordEncoder passwordEncoder,
            JwtService jwtService,
            AuthenticationManager authenticationManager,
            UserDetailsService userDetailsService) {
        this.userRepositoryPort = userRepositoryPort;
        this.passwordEncoder = passwordEncoder;
        this.jwtService = jwtService;
        this.authenticationManager = authenticationManager;
        this.userDetailsService = userDetailsService;
    }

    /**
     * Registers a new user in the system.
     * @param request The registration request details.
     * @return AuthResponse containing JWT token and user info.
     * @throws CustomAuthenticationException if username already exists.
     */
    @Override
    @Transactional
    public AuthResponse register(RegisterRequest request) {
        if (userRepositoryPort.existsByUsername(request.getUsername())) {
            throw new DuplicateUsernameException("Username '" + request.getUsername() + "' already exists.");
        }

        User user = new User(
                null, // ID will be generated by DB
                request.getUsername(),
                passwordEncoder.encode(request.getPassword()), // Encode password
                request.getRole(),
                true, // Enabled by default
                LocalDateTime.now()
        );

        User savedUser = userRepositoryPort.save(user);

        // Generate token for the newly registered user
        UserDetails userDetails = userDetailsService.loadUserByUsername(savedUser.getUsername());
        String jwtToken = jwtService.generateToken(userDetails);

        return new AuthResponse(
                jwtToken,
                savedUser.getUsername(),
                savedUser.getRole(),
                jwtService.getJwtExpiration()
        );
    }

    /**
     * Authenticates a user and returns a JWT token.
     * @param request The login request details.
     * @return AuthResponse containing JWT token and user info.
     * @throws CustomAuthenticationException if authentication fails.
     */
    @Override
    public AuthResponse login(LoginRequest request) {
        // Authenticate using Spring Security's AuthenticationManager
        authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(
                        request.getUsername(),
                        request.getPassword()
                )
        );

        // If authentication is successful, load user details and generate token
        UserDetails userDetails = userDetailsService.loadUserByUsername(request.getUsername());
        String jwtToken = jwtService.generateToken(userDetails);

        // Get the domain user to return role and username
        User user = userRepositoryPort.findByUsername(request.getUsername())
                .orElseThrow(() -> new CustomAuthenticationException("User not found after successful authentication."));


        return new AuthResponse(
                jwtToken,
                user.getUsername(),
                user.getRole(),
                jwtService.getJwtExpiration()
        );
    }
}
